### ISSUE TITLE
Missing testharness files in version 4.0.1

### ISSUE THREAD

**Issue by MattiasBuelens** [domenic/wpt-runner#25]
The `testharness/` files are missing in the tarball of version 4.0.1 as published to npm. (See on [unpkg](https://unpkg.com/browse/wpt-runner@4.0.1/))

The package contents should look like this:
```
├── LICENSE.txt
├── README.md
├── bin
│   └── wpt-runner.js
├── lib
│   ├── console-reporter.js
│   ├── internal
│   │   ├── handlers.js
│   │   ├── serve.js
│   │   └── sourcefile.js
│   ├── testdriver-dummy.js
│   └── wpt-runner.js
├── package.json
└── testharness
    ├── idlharness.js
    ├── testharness.js
    └── webidl2
        └── lib
            └── webidl2.js
```

But in version 4.0.1, they look like this:
```
├── LICENSE.txt
├── README.md
├── bin
│   └── wpt-runner.js
├── lib
│   ├── console-reporter.js
│   ├── internal
│   │   ├── handlers.js
│   │   ├── serve.js
│   │   └── sourcefile.js
│   ├── testdriver-dummy.js
│   └── wpt-runner.js
└── package.json
```

This breaks users of wpt-runner, for example the Streams tests:
```
Error: ENOENT: no such file or directory, open '/home/runner/work/streams/streams/reference-implementation/node_modules/wpt-runner/testharness/testharness.js'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:126:14
    at FSReqCallback.oncomplete (fs.js:179:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/runner/work/streams/streams/reference-implementation/node_modules/wpt-runner/testharness/testharness.js'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ wpt: `npm run pretest && node --expose_gc run-web-platform-tests.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ wpt script.
```

Looks like it's time for a version 4.0.2? 😛

**Comment by domenic** [comment]
Oops! Darn submodules, they didn't init on a new computer. Published.
